# Generated by Django 3.2.10 on 2022-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
